### ISSUE TITLE
Organization - define the basics

### ISSUE THREAD

**Issue by afinika** [help2022-ukr/help2022#15]
**TODO**

- [x] define the problems
- [x] define the areas of actions
- [x] define the solutions 
- [x] define the risks
- [x] define the unknowns 
- [x] define the needs

Project doc
https://docs.google.com/document/d/1ro2EjWv6CaGWU4F0GwiCbhXbkhvYYB-aV0_vT87biCU/edit?usp=sharing

**Comment by afinika** [comment]
Needs:
1. development - min 2 volunteers to maintain and build the platform
2. 1 volunteer to check the quality of the content daily 
3. 1 volunteer to publish regularly in all communities and chats 
4. 2 volunteers to research the situation, identify the problems and come up with solutions
